// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qothiaalyhdfuesmvcvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdGhpYWFseWhkZnVlc212Y3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MTAwOTAsImV4cCI6MjA0OTQ4NjA5MH0.4eKrXkqGeFRZeZsgzo0tR0G9ULR9EC3F9Z5HKnet7Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);